name: Build and Test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build_type: [Release, Debug]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build
      - uses: actions/checkout@v3
      - name: Configure
        run: cmake -S . -B build/ -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Build
        run: cmake --build build/ --target all --config ${{ matrix.build_type }}
      - name: Test
        run: |
          cd build/
          ctest --output-on-failure
          cd ..
